# Generated by Django 3.0.7 on 2020-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='confirmee',
            new_name='validee',
        ),
        migrations.AddField(
            model_name='panier',
            name='confirme',
            field=models.BooleanField(default=False),
        ),
    ]
