# Generated by Django 3.0.7 on 2020-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200616_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
