# Generated by Django 3.0.7 on 2020-07-15 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200715_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
