# Generated by Django 3.0.7 on 2020-07-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_commande_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='facture',
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandefacture', to='bill.Commande'),
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignesCmd', to='bill.Commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Produit'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.UniqueConstraint(fields=('produit', 'commande'), name='produit-commande'),
        ),
    ]
